### ISSUE TITLE
Editing variables is inconsistent

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#113]
Hello there, it's me again 😅 

I've been messing up with editing variables and I've noticed some inconsistencies. Editing through the scopes works as expected, but using the watches doesn't: the variable's name ends up in the editing prompt, and while the variable is edited, it's a bit buggy:
![image](https://user-images.githubusercontent.com/84649544/174635538-6ce5ab3e-1a4b-4f9f-b12d-ecd788c8585e.png)
After editing:
![image](https://user-images.githubusercontent.com/84649544/174635915-5714b2ee-2419-4ef4-bdec-cecb57563d55.png)

I've tested this with _lldb-vscode_, which shows the behaviour described and _debugpy_ which is actually worse: using the equals sign gives a syntax error.

**Comment by rcarriga** [comment]
The editing in watches is not supposed to change the value of the top level expression. Instead it is editing the expression to watch.

So when you set the watch to be `someVariable = 5`, you're telling nvim-dap-ui to evaluate that every frame. So when python gives you a syntax error, it's actually correct because that is a statement, not an expression. lldb-vscode is actually behaving weirdly here by evaluating a statement.

**Comment by igorlfs** [comment]
>The editing in watches is not supposed to change the value of the top level expression. Instead it is editing the expression to watch.

Oh, I see.
