### ISSUE TITLE
Handle evaluating expressions

### ISSUE THREAD

**Issue by igorlfs** [rcarriga/nvim-dap-ui#141]
Hello there,

CodeLLDB throws the following error when evaluating expressions (eg, when using `dapui.eval()`):

```
[debug-adapter stderr] [ERROR codelldb::debug_session] Internal debugger error: Expected non-zero handle value
```
I'm pretty sure this is something specific with [CodeLLDB](https://github.com/vadimcn/vscode-lldb/blob/bc36db0bafd1b77d1cc9aa2dc9d69b221c7d4ae8/adapter/src/handles.rs#L20), but it works just fine when using nvim-dap's builtin `hover()` from `dap.ui.widgets`. The error itself seems to be harmless, but it populates the repl quickly when watching expressions.

**Comment by rcarriga** [comment]
As you said this is a CodeLLDB issue, not a client issue so there's not much I can do to diagnose.

I can tell you though that this is not an issue in nvim-dap-ui vs nvim-dap. The reason you're not seeing the error with nvim-dap's hover widget is that it will check the variables it has stored in state for the expression before sending to the debugger and use it if found, so it's essentially caching. You can disable this caching by changing this line https://github.com/mfussenegger/nvim-dap/blob/master/lua/dap/ui/widgets.lua#L266 from `if variable then` to `if false then`.

You may actually see a different error because nvim-dap doesn't use the correct "context" argument when evaluating and it seems CodeLLDB is fussy about that.

**Comment by igorlfs** [comment]
> As you said this is a CodeLLDB issue, not a client issue so there's not much I can do to diagnose.

I've opened a discussion on their repo. As always, thanks for the support!
