### ISSUE TITLE
Disconnect/close not closing dap-ui interface when debugging C

### ISSUE THREAD

**Issue by ebiscaia** [rcarriga/nvim-dap-ui#244]
Hi,

I tried the commands `*.dap.disconnect()` and `*.dap.close()` and although they seem to work (variables disappear and console shows `[Process exited 0]`, the ui does't close. I tried the same with a Python program and everything went fine. If I continue the debugging to its end the ui closes fine too.

> Edit:
> I forgot to mention that I am using cpptools with gdb.

In this case, is there any additional command or setting I may be missing?

Thanks.

**Comment by rcarriga** [comment]
This is because of the events that are emitted by the adapter are different.
I'd suggest trying this https://github.com/rcarriga/nvim-dap-ui/issues/147#issuecomment-1297126808. If that doesn't work you can check the events by setting the nvim-dap log level to debug and reproducing. See `:h *dap.set_log_level()`
