### ISSUE TITLE
feat: Dedicated tab for nvim dap ui

### ISSUE THREAD

**Issue by mikesmithgh** [rcarriga/nvim-dap-ui#249]
Feature request: I'd like to have similar behavior to the plugin [diffview.nvim](https://github.com/sindrets/diffview.nvim) such that you can toggle dap-ui and it will open in a dedicated tab. Then if you run the debugger it can automatically focus the tab with dap-ui.

Currently, I create a separate tab to make code changes and navigate back to the tab with dap-ui when debugging. This works okay for the most part, but I'd like it to autofocus the dedicated tab when the debugger is triggered.

**Comment by rcarriga** [comment]
You can do this with some event listeners with something like this https://github.com/rcarriga/nvim-dap-ui/issues/122#issuecomment-1206389311

This isn't built-in functionality because there are just too many potential requirements to handle, which is why whole plugins are dedicated to just opening complex window layouts (e.g. nui.nvim)

**Comment by mikesmithgh** [comment]
@rcarriga  makes senses. Thanks! I'll check out the event listeners seems pretty straight forward 👍
