### ISSUE TITLE
Dealing with long error messages

### ISSUE THREAD

**Issue by MJohnson20** [rcarriga/nvim-dap-ui#327]
When using the UI if an exception message is particularly long it scrolls off the right hand side of the screen sometimes cutting off important information. Is there anyway of dealing with this and viewing the full error message, for example by making it wrap?

**Comment by CluelessCPU** [comment]
While I think that some more discussion should be had on how generally this should be handled, if you're using kickstart.nvim or something derived from it, using `<leader>e` opens the error message in a floating window. #nvim-lua/kickstart.nvim#295 . If you're not using kickstart, you're going to want to bind the `vim.diagnostic.open_float()` function to something convenient.

More generally, this issue seems to come from how virtual text is handled in neovim, which isn't necessarily something that dapui can control. It should probably be noted in the documentation of one of these things but it was quite a journey to figure out.

**Comment by rcarriga** [comment]
DAP UI doesn't set the diagnostic message at all, nvim-dap does so I'm closing as unrelated. Thanks @CluelessCPU for the explainer/workaround.

**Comment by Mechanosec** [comment]
<img width="1359" alt="image" src="https://github.com/user-attachments/assets/2390914b-5c3e-4c73-be3e-c85a4778c94f">
