### ISSUE TITLE
Ability to move cursor to a certain window

### ISSUE THREAD

**Issue by vxio** [rcarriga/nvim-dap-ui#63]
Is there a function I can call to move my cursor to the `Scopes` window? Or any of the debug windows?

**Comment by rcarriga** [comment]
There is nothing like that builit-in but there are many plugins to achieve this for windows in general (e.g. https://gitlab.com/yorickpeterse/nvim-window). Otherwise you could write a small helper function to jump between the `dapui` windows. Each one has a constant filetype and buffer name  so they are easy to interact with in scripts

**Comment by vxio** [comment]
Good point, I'll do that. Thanks and feel free to close this issue!
