### ISSUE TITLE
Show lines longer than the sidebar window width

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#92]
![image](https://user-images.githubusercontent.com/11404453/162329194-2497f2b8-3798-413a-8bc3-0f03e0688560.png)

Looking at https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/internal/drawer/hover_popup.vim and https://github.com/przepompownia/vim-arctgx/blob/5235a545c35c591a957d83608110e898aa221971/plugin/dump.lua I wrote
https://github.com/przepompownia/vim-arctgx/blob/27ddb4fa65d3862596841fbb8b932cf4ad19e11b/lua/arctgx/lineHover.lua to display lines longer than the sidebar window width. 

Given this module available as `arctgx.lineHover`, try
```
lua vim.api.nvim_create_autocmd('FileType', {pattern = 'dapui_scopes', callback = require('arctgx.lineHover').enableForWindow})
```
I can settle for using it locally but it could be part of nvim-dap-ui. If so then @rcarriga can you help me how to attach those autocommands in a good way?

**Comment by rcarriga** [comment]
I love the idea, and thanks for offering to implement! This would be best served in the [canvas.lua](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/render/canvas.lua) file. As part of the `render_buffer` function we could add a `CursorHold` autocmd with the `<buffer>` setting.

One thing to note is that we can't use the new autocmd callback as it's not in stable yet and I don't want to require nightly, but I'm already working around this by exposing the mappings throug.h a module function (see [here](https://github.com/rcarriga/nvim-dap-ui/blob/master/lua/dapui/render/canvas.lua#L146)). Once 0.7 is released for a bit and people have time to update I'll be happy to switch to using lua callbacks.

Also since I haven't put together a contributing doc I'll just mention that all code should use `snake_case` and if the code for this ends up being a bit chunky it might be worth sticking into it's own module but I'll have to see the end result first. The canvas file is already a bit messy and I'd like to clean it up (some day :sweat_smile:)

If you have questions feel free to open a WIP PR and add comments/questions :smile:

**Comment by przepompownia** [comment]
I added initial `.editorconfig` to use by sumneko lua LS. It's mostly copied from the example file. Some rules are only reported (snake case for example), some can be applied to LSP's textDocument/format.

I prepared  `make long-line-hover` in https://github.com/przepompownia/dap-ui-test (notice changed URL and branch to submodule)
![image](https://user-images.githubusercontent.com/11404453/162509452-7efaf15a-bdcd-42c5-82eb-71130131d648.png)

Currently I need to debug why the same buffer number is used to autocommands. Any idea before I find it?
